# Generated by Django 2.0.5 on 2019-09-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='category',
        ),
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.ManyToManyField(to='bids.Category'),
        ),
    ]
