# Generated by Django 2.2.4 on 2019-08-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('currently', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_bids', models.IntegerField()),
                ('location', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=50)),
                ('started', models.DateTimeField()),
                ('ends', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
