# Generated by Django 2.0.5 on 2019-09-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_recommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='auctionId',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='userId',
            new_name='user',
        ),
    ]
