# Generated by Django 2.2.5 on 2019-09-27 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_auto_20190927_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='started',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
