# Generated by Django 2.2.4 on 2019-08-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='country',
            field=models.CharField(default='Greece', max_length=50),
        ),
        migrations.AlterField(
            model_name='auction',
            name='currently',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='first_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='number_of_bids',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='started',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
