# Generated by Django 2.2.4 on 2019-08-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_auto_20190830_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.CharField(default='Empty', max_length=500),
        ),
        migrations.AlterField(
            model_name='auction',
            name='ends',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
