# Generated by Django 2.2.5 on 2019-09-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_auto_20190927_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
