# Generated by Django 2.2.5 on 2019-09-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_auto_20190911_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
