# Generated by Django 2.2.5 on 2019-09-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_auction_is_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
